sushiProjet/src/Entity/Livreur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LivreurRepository")
 */
class Livreur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $Telephone;

    /**
     * @ORM\Column(type="integer")
     */
    private $NombreLivraisons;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $TempsLivraison;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Absences;

    /**
     * @ORM\Column(type="integer")
     */
    private $EtatCommande;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getNombreLivraisons(): ?int
    {
        return $this->NombreLivraisons;
    }

    public function setNombreLivraisons(int $NombreLivraisons): self
    {
        $this->NombreLivraisons = $NombreLivraisons;

        return $this;
    }

    public function getTempsLivraison(): ?string
    {
        return $this->TempsLivraison;
    }

    public function setTempsLivraison(string $TempsLivraison): self
    {
        $this->TempsLivraison = $TempsLivraison;

        return $this;
    }

    public function getAbsences(): ?int
    {
        return $this->Absences;
    }

    public function setAbsences(?int $Absences): self
    {
        $this->Absences = $Absences;

        return $this;
    }

    public function getEtatCommande(): ?int
    {
        return $this->EtatCommande;
    }

    public function setEtatCommande(int $EtatCommande): self
    {
        $this->EtatCommande = $EtatCommande;

        return $this;
    }
}

sushiProjet/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;
use Doctrine\Common\Persistence\ObjectManager;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/inscription",name="security_registration")
     */
    public function registration( Request $request,ObjectManager $manager,
    UserPasswordEncoderInterface $encoder){

        $user = new User();

        $form = $this->createForm(RegistrationType::class,$user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $manager->persist($user);
            $manager->flush();

            return $this->redirectToRoute('security_login');
        }

        return $this->render('security/registration.html.twig',[
            'form'=>$form->createView()


        ]);
}

    /**
     * @Route("/connexion",name="security_login")
     */
    public function login(){
        return $this->render('security/login.html.twig');
    }

    /**
     * @Route("/deconnexion",name="security_logout")
     */
    public function logout(){

    }

}

sushiProjet/templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

sushiProjet/templates/security/login.html.twig
{% extends 'base.html.twig' %}


{% block body %}


    <h1>Connexion ! </h1>

    <form action="{{ path('security_login') }}" method="post">

        <div class="form-group">
            <input placeholder="Email" required name="_username" type="text" class="form-control">
        </div>

        <div class="form-group">
            <input placeholder="Mot de passe" required name="_password" type="password" class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success"> Connexion !  </button>

        </div>

    </form>

{% endblock %}

sushiProjet/templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Inscription</h1>

    {{ form_start(form) }}

    {{ form_row(form.username, {'label':'Nom d\'utilisateur'}) }}
    {{ form_row(form.email, {'label':'Email'}) }}
    {{ form_row(form.password, {'label':'Mot de passe'}) }}
    {{ form_row(form.confirm_password , {'label':'Confirmer mot de passe'}) }}

    <button type="submit" class="btn-success">Inscription ! </button>
    {{ form_end(form) }}





{% endblock %}